### PR TITLE
add delete method

### LINKED ISSUE #18: Implement deleting all tutorials in bulk

### PR DESCRIPTION
**Pull request by naoharu**
# What we do in this PR
Deleting all tutorials.

# What we want the reviewer to check
You can delete all tutorials by clicking the red button.
This PR will close #18

### CODE REVIEW

**Comment by naoharu** [comment]
This PR will close #18

**Comment by naoharu** [comment]
Hi @toshihue Can you review this also? Thanks.

**Comment by toshihue** [comment]
@naoharu I have confirmed all tutorials can be deleted from UI. Thank you!
image

**Comment by toshihue** [comment]
> Hi @toshihue Can you review this also? Thanks.

I have confirmed all tutorials can be deleted from UI. Thank you.
image

**Review by toshihue — APPROVED** [review]
LGTM

**Pull request merged**
