### PR TITLE
replace "ID" to "Id",  and  add API to get single tutorial

### PR DESCRIPTION
**Pull request by naoharu**
# What we do in this PR
- The variable name ID (upper case) that held the primary key in the server-side go controller was changed to id (lower case) because it was unnatural.

- The variable name ID of the model of go on the server side was changed to Id. (The leading capital letter is [a constraint on the variable name of the model](https://chat.openai.com/share/71ae7dce-5e1e-4d62-a240-9559cf655b0c).)

- The variable id on the client side was changed to Id to make it consistent with automatic mapping.

- Added API to retrieve a single tutorial.

# What we would like reviewer to check
- You can go from the tutorial list page to the detail page.
- Tutorials can be edited from the detail page.
- Tutorials can be published from the detail page.
- Tutorials can be un-published from the detail page.
- Tutorials can be deleted from the detail page.

# Screen shots
image

---

image

---
image

---

### CODE REVIEW

**Comment by naoharu** [comment]
Hi @toshihue  
I have created an API to get a single tutorial by specifying an id, and then the application starts working. I think that this API was the last piece of the puzzle.
Could you please review the behavior of the whole application?

**Comment by naoharu** [comment]
No, the Get Single Tutorial API is not the last one.
Search and Remove all are still remaining.

**Comment by naoharu** [comment]
This PR will solve 
https://github.com/toshi-nao/web-app-sample/issues/21
https://github.com/toshi-nao/web-app-sample/issues/22

**Comment by toshihue** [comment]
> Hi @toshihue I have created an API to get a single tutorial by specifying an id, and then the application starts working. I think that this API was the last piece of the puzzle. Could you please review the behavior of the whole application?

It worked!
image

**Review by toshihue — APPROVED** [review]

**Pull request merged**
