### PR TITLE
CRUD - Create a single tutorial 

### PR DESCRIPTION
**Pull request by naoharu**

### CODE REVIEW

**Comment by naoharu** [comment]
## Initial data
image

## Create
image

## Result
image

**Comment by naoharu** [comment]
HTTP Request sample is [here](https://github.com/toshi-nao/web-app-sample/issues/4)

@toshihue Please can you review this PR also?

**Comment by toshihue** [comment]
> HTTP Request sample is [here](https://github.com/toshi-nao/web-app-sample/issues/4)
> 
> @toshihue Please can you review this PR also?

`$`set`:{` should not be in the inserted tutorial document. So I just removed it. I also change the method names in `tutorial_controller.go`. See this commit: https://github.com/toshi-nao/web-app-sample/pull/12/commits/8970435604bbde6bcff7e1ae8cbf924d2af50752

An inserted document example:
image

**Comment by naoharu** [comment]
@toshihue Thanks for pointing out! I have also confirmed that it works and will merge it.

**Pull request merged**
